name: "Build Android release APK"
branding:
  icon: "package"
  color: "red"
description: "Build Android release APK and upload as a github release."
author: "VladDaniliuk"
inputs:
  GITHUB_TOKEN:
    description: "Github secret token to allow automated publishing of APK to release."
runs:
  using: "docker"
  image: "Dockerfile"
